biblioteca/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'libros.views.inicio', name='inicio'),
    url(r'^libros/nuevo/$','libros.views.nuevo_libro' , name='libros_nuevo'),
    url(r'^titulos/$','libros.views.listado_libros' , name='libros_listado'),
    url(r'^libro/(?P<id_libro>\d+)$','libros.views.detalle_libro', name='libro_detalle'),
    url(r'^autores/nuevo/$','autores.views.nuevo_autor', name='autores_nuevo'),
    url(r'^autores/$','autores.views.listado_autores', name='autores_listado'),
    url(r'^libro/(?P<id_libro>\d+)/prestamo','prestamo.views.nuevo_prestamo', name='prestamo_nuevo'),
    #url(r'^ingresar/$','prestamo.views.get_lector_prestamo'),


)



if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

    urlpatterns += staticfiles_urlpatterns()

autores/models.py
from django.db import models
from django_countries.fields import CountryField

class Autor(models.Model):
	nombre = models.CharField(max_length=20, unique=True, blank=False)
	nacionalidad = CountryField()

	def __unicode__(self):
 		return self.nombre

libros/models.py
from django.db import models
from autores.models import Autor

class Libro(models.Model):

    area = models.CharField(max_length=50, verbose_name='Area',
           null=True)

    titulo = models.CharField(max_length=50, verbose_name='Titulo',
             unique=True, blank=False)


    editorial = models.CharField(max_length=50, verbose_name='Editorial',
                null=True)

    disponible_fisico = models.BooleanField(verbose_name='Disponible fisico', default=False)

    fecha_publicacion = models.DateField(verbose_name='Fecha de publicacion', null=True)

    #Archivos asociados
    cover_url = models.ImageField(upload_to='covers', verbose_name='Cover', blank=True, null=True)

    digital_url = models.FileField(upload_to='digital', verbose_name='Archivo Digital', blank=True, null=True)

    #Restricciones de dominio, tradicionalmente se tenia que hacer otra tabla, con django podemos hacer un vector
    #que contenga las elecciones.

    FACULTAD_CHOICES = (
        (u'1', u'Derecho'),
        (u'2', u'Ingenieria De Sistemas'),
        (u'3', u'Psicologia'),
        (u'4', u'Administracion de empresas'),
    )

    facultad = models.CharField(max_length=1, choices=FACULTAD_CHOICES, null=True)

    #Relacion muchos a muchos, para ver el codigo sql generado por este modelo ejecutar " $./manage.py sql libros"


    autor = models.ForeignKey(Autor)

    def __unicode__(self):
        return self.titulo

prestamo/models.py
from django.db import models
from libros.models import Libro
from django.contrib.auth.models import User

class Prestamo(models.Model):
    lector = models.ForeignKey(User, null=True)
    fecha_prestamo = models.DateTimeField(auto_now=True, null=True)
    libro = models.ForeignKey(Libro, null=True)


    def __unicode__(self):
        return unicode(self.lector)

autores/forms.py
#encoding:utf-8
from django.forms import ModelForm
from django import forms
from .models import Autor

class AutorForm(forms.ModelForm):

	nombre = forms.CharField(widget=forms.TextInput(attrs={'class': 'error','placeholder': 'Julio César'}))
    	class Meta:
        	model = Autor
        	fields = ['nombre','nacionalidad']

libros/forms.py
#encoding:utf-8
from django.forms import ModelForm
from django import forms
from .models import Libro
from autores.models import Autor

class LibroForm(forms.ModelForm):

	#autores = list(Autor.objects.values('nombres'))

	titulo = forms.CharField(widget=forms.TextInput(attrs={'class': 'error','placeholder': 'Javascipt: The Good Parts'}))
	#autor = forms.ChoiceField(widget=forms.Select(attrs={'class': 'error'}), choices = autores)
	area = forms.CharField(widget=forms.TextInput(attrs={'class': 'error','placeholder': 'Programación'}))
	editorial = forms.CharField(widget=forms.TextInput(attrs={'class': 'error','placeholder': "O'Reilly media"}))
	fecha_publicacion = forms.CharField(widget=forms.TextInput (attrs={'placeholder': "AA/MM/DD"}))
    	class Meta:
        	model = Libro
        	fields = ['titulo','area','autor','editorial','cover_url','facultad','disponible_fisico','digital_url','fecha_publicacion']

prestamo/forms.py
#encoding:utf-8
from django import forms
from .models import Prestamo


class PrestamoForm(forms.ModelForm):

    class Meta:
            model = Prestamo
            fields = []

autores/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.shortcuts import render, redirect
from .forms import AutorForm
from autores.models import Autor

def nuevo_autor(request, template='autorForm.html'):
    form = AutorForm()
    if request.method == "POST":
    	form = AutorForm(request.POST)
        if form.is_valid():
        	form.save()
		return redirect('/libros/nuevo/')

    kwvars = {
        "form": form,
    }
    return render_to_response(template, kwvars, context_instance=RequestContext(request))

def listado_autores(request):
    autores = Autor.objects.all()
    return render(request,'autoresListado.html', {'autores':autores})

libros/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404
from django.shortcuts import render
from .models import Libro
from autores.models import Autor
from .forms import LibroForm


def inicio(request):
    autores = Autor.objects.all()
    libros = Libro.objects.all()
    return render(request, 'inicio.html', {'autores': autores, 'libros': libros})


def nuevo_libro(request, template='libroForm.html'):
    form = LibroForm()
    if request.method == "POST":
        form = LibroForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return render(request, 'libroNuevo.html')

    kwvars = {
        "form": form,
    }
    return render_to_response(template, kwvars, context_instance=RequestContext(request))


def listado_libros(request):
    autores = Autor.objects.all()
    libros = Libro.objects.all()
    return render(request, 'librosListado.html', {'autores': autores, 'libros': libros})


def detalle_libro(request, id_libro, template='libroDetalle.html'):
    libro = get_object_or_404(Libro, pk=id_libro)
    return render_to_response(template, {'libro': libro}, context_instance=RequestContext(request))

prestamo/views.py
from django.shortcuts import render_to_response, get_object_or_404, render
from django.template import RequestContext
from django.http import  HttpResponseRedirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from libros.models import Libro
from prestamo.models import Prestamo

def nuevo_prestamo(request, id_libro, template='prestamoForm.html'):

    libro = get_object_or_404(Libro, pk=id_libro)
    form = AuthenticationForm()


    if request.method == 'POST' :
        form = AuthenticationForm(request.POST)
        if form.is_valid:
            usuario = request.POST ['username']
            clave = request.POST ['password']
            acceso = authenticate(username = usuario, password = clave)
            if acceso is not None:
                if acceso.is_active:
                    login(request, acceso)
                    # Obtener usuario
                    usuario = request.user
                    # Insertar registro en "prestamo"
                    prestamo = Prestamo()
                    prestamo.lector = usuario
                    prestamo.libro = libro
                    prestamo.save()
                    # Cambiar la disponibilidad del libro
                    libro.disponible_fisico = False
                    libro.save()

                    return render( request, 'prestamoExito.html')
                else :
                    return render_to_response ('noactivo.html', context_instance=RequestContext(request))
            else :
                return render_to_response ('nousuario.html', context_instance=RequestContext(request))
    else:
        form = AuthenticationForm()
        return render_to_response('prestamoForm.html', {'form':form , 'libro': libro}, context_instance=RequestContext(request))

templates/autorForm.html
{% extends 'base.html' %}
{% block contenido %}
<br>
   <h4><a href="/">Inicio</a> / Nuevo autor</h4>
    <div class="large-8 columns">
        <div class=" panel row">
       
        <form action='' method='POST'>
            <div class="row">
                <div class="  large-12 columns">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            <label> Nombre:
                            {{ form.nombre }}
                            </label>
                            {% if form.nombre.errors %}
                     
                              {% for error in form.nombre.errors %}
                              <small class="error">
                                  {{ error|escape }}
                              </small>
                              {% endfor %}
                          {% endif %}                       
                </div>
            </div>
            <br>
            <div class="row">
               <div class="large-4 columns">
                            <label > Nacionalidad: 
                             {{ form.nacionalidad }}
                            </label>
                            {% if form.nacionalidad.errors %}
                     
                              {% for error in form.nacionalidad.errors %}
                              <small class="error">
                                  {{ error|escape }}
                              </small>
                              {% endfor %}
                          {% endif %}
                   </div>
              <div class="  large-4 columns">
                  
              </div>
            </div>
            <input style="background-color:#7bac0f" class="button tiny " type='submit' value='Registrar y agregar datos del libro'/>
        </form>

    </div>
{% endblock %}

templates/autoresListado.html
{% extends 'base.html' %}

{% block contenido %}
<br>
  <div class="large-8 columns">
    <div class="row" data-equalizer>

      <nav id="menu_estanteria">
        <ul>
          <li><strong>Descubre:</strong></li>
          <li>|</li>
          <li> <a href="/titulos">Títulos </a>  </li>
          <li>|</li>
          <li><a style="color:red;"  href="/autores">Autores</a> </li>
          <li>|</li>
          <li><a href="">Temas</a> </li> 
          <li>|</li>
          <li><a href="">Facultades</a></li>
          <li>|</li>
        </ul>
      </nav>

      <div  class=" opciones columns"><h3> Todos los Autores</h3> 

     
        <div id="opciones-vista">
          <strong>Vista:</strong>  <a href="#listado" onclick="return show('lista','galeria');">Listado</a> | <a href="" onclick="return show('galeria','lista');">Galería</a>
        </div>
        
      </div>
          
  <div class="columns" id="users">
    <input class="search" placeholder="Buscar en la tabla" />
    <button class="sort" data-sort="nombre">
    Ordenar por nombre
    </button>
    <table>
    <thead>
    <tr>
      <th width="200">Nombre</th>
      <th  width="200"  >Nacionalidad</th>
    </tr>
    </thead>
    <!-- IMPORTANT, class="list" have to be at tbody -->
    <tbody class="list">
      {% for autor in autores %}
      <tr>
        <td class="nombre">{{autor.nombre}} </td>
        <td class="nacionalidad">{{autor.get_nacionalidad_display}}</td>
              </tr>
             {% endfor %}
          </tbody>
          </table>
  </div>
</div>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> Biblioteca </title>
    <link rel="stylesheet" href="{{STATIC_URL}}css/foundation.css" />
    <link rel="stylesheet" href="{{STATIC_URL}}css/biblioteca.css">
    <script type="text/javascript" src="{{STATIC_URL}}js/vendor/modernizr.js"></script>
    <script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-56163744-1', 'auto');
    ga('send', 'pageview');

  </script>
  </head>

  <body style="background-color:;">


   <div class="row">

    <div class="large-12 columns">

       <div class="row">

        <div class="large-12 columns">

          <nav class="top-bar" data-topbar>
            <ul class="title-area">

              <li class="name">
                <h1>
                  <a href="/">
                    Biblioteca v0.1
                  </a>
                </h1>
              </li>
              <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
            </ul>

            <section class="top-bar-section">

              <ul class="left">

                <li class="has-form">
                  <div class="row collapse">
                    <div class="large-8 small-9 columns">
                     <input type="text" placeholder="Título o autor ">
                   </div> <div class="large-4 small-3 columns">
                   <a href="/titulos" style="background-color:#009cde"class="alert button expand">Buscar</a>
                 </div>
               </div>
             </li>

              </ul>

              <ul class="right">
                <li class="divider"></li>
                <li class="has-dropdown">
                  <a href="#">Consultas</a>
                  <ul class="dropdown">
                    <li><label>Consultas</label></li>
                    <li class="has-dropdown">
                      <a href="#" class="">Filtrar</a>
                      <ul class="dropdown">
                        <li><a href="#">Disponible fisico</a></li>
                        <li><a href="#">Disponible digital</a></li>
                      </ul>
                    </li>
                    <li><a href="#">Autores</a></li>
                    <li><a href="#">Areas</a></li>
                    <li class="divider"></li>
                    <li><label> Por facultades </label></li>
                    <li><a href="#">Derecho</a></li>
                    <li><a href="#">Ingenieria de Sistemas</a></li>
                    <li><a href="#">Psicologia</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Ver todos →</a></li>
                  </ul>
                </li>
                <li class="divider"></li>
                <li><a href="/libros/nuevo/">Agregar libro</a></li>

                <li class="divider"></li>
                <li class="has-dropdown">
                  <a style="background-color:#7BAC0F" href="/admin/">Ingresar</a>
                  <!-- <ul class="dropdown">
                    <li><a href="#">Prestamos</a></li>
                    <li><a href="#">Descargas</a></li>
                    <li><a href="#">Perfil</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Salir</a></li>
                  </ul>-->
                </li>
              </ul>
            </section>
          </nav>

        </div>
      </div>

       <div class="row">

              <div class="large-4 small-12 columns">

          <img src="{{STATIC_URL}}img/logo.png">

          <div  class=" panel">
            <h4>Sobre el proyecto</h4>
            <p class="subheader"> Proyecto final para el curso de base de datos, le proyecto es completamente <strong>Open Source</strong> , la idea se puede proyectar para impletarlo en la universidad ya que esta  no cuenta con un sistema de catalogo y prestamo eficiente para los recursos de la biblioteca.
            </p>

            <p>Si se animan a contribuir pueden leer la documentación para que entiendan la estructura del proyecto (como funcionan los modelos, la base de datos diseño y conexión, las vistas, etc..), el repositorio esta disponible en Github. </p>
              <a style="background-color:#7BAC0F" href="https://github.com/uzi200/biblioteca-django" class="button tiny">Repositorio</a>
              <a href="http://biblioteca.uzi200.me/docs"class="button tiny">Documentación</a>
          </div>

          <a href="https://github.com/uzi200/biblioteca-django"><img style="position: absolute; top: 0; left: 0; border: 0;" src="https://camo.githubusercontent.com/121cd7cbdc3e4855075ea8b558508b91ac463ac2/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f677265656e5f3030373230302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_left_green_007200.png"></a>
          <div class="panel callout radius">
            <h4> Sobre el autor</h4>
              <strong> Julio César Castellanos </strong> <br>
              +57 301 508 86 87 <br>
              Mail - <a href="mailto:julioc@protonmail.ch"> julioc@protonmail.ch</a><br>

              WWW - <a href="http://blog.uzi200.me/about">blog.uzi200.me/about</a><br>

              Twitter - <a href="http://twitter.com/@UZI200">@UZI200</a> <br>

              Github - <a href="http://github.com/uzi200"> UZI200</a>

              <br><br>
            <h5>Otros proyectos</h5>

              <a href="http://omnipresent.uzi200.me">omnipresent.uzi200.me</a><br>
              <a href="http://chasser.co">chasser.co</a><br>

          </div>

        </div>


    {% block contenido %} {% endblock%}



      <footer class="row">
        <div class="large-12 columns"><hr/>
          <div class="row">

            <div class="large-5 columns">
              <p>Julio César 2014</p>
            </div>

            <div class="large-6 columns">
              <ul class="inline-list right">
                <li><a href="http://biblioteca.uzi200.me/docs">Documentación</a></li>
              	<li><a href="http://blog.uzi200.me/about">Sobre</a></li>

              </ul>
            </div>

          </div>
        </div>
      </footer>
    </div>
  </div>

    <script src="{{STATIC_URL}}js/vendor/jquery.js"></script>
    <script src="{{STATIC_URL}}js/foundation.min.js"></script>
    <script src="{{STATIC_URL}}js/list.js"></script>
    <script src="{{STATIC_URL}}js/biblioteca.js"> </script>
    <script>
      $(document).foundation();
    </script>
  </body>
</html>

templates/ingresar.html
{% extends 'base.html' %}

<h1> Tus datos </h1>

{% block contenido %}
          <form id = 'formulario' method = 'post' action='' > {% csrf_token %}
          <table>{{formulario}}</table>
          <p><input type = 'submit' value = 'Ingresar' /></p>
          </form>
{% endblock %}

templates/inicio.html
{% extends 'base.html'%}

{% block contenido %}
<br>
  <div class="large-8 columns">
    <div class="row" data-equalizer>



      <nav id="menu_estanteria">
        <ul>
          <li><strong>Descubre:</strong></li>
          <li>|</li>
          <li > <a href="/titulos">Títulos </a>  </li>
          <li>|</li>
          <li><a href="/autores">Autores</a> </li>
          <li>|</li>
          <li><a href="">Temas</a> </li>
          <li>|</li>
          <li><a href="">Facultades</a></li>
          <li>|</li>
        </ul>
      </nav>

      <div  class=" opciones columns"><h3> Últimos libros</h3>

        <div id="opciones-vista">
          <strong>Vista:</strong>  <a href="#listado" onclick="return show('lista','galeria');">Listado</a> | <a href="" onclick="return show('galeria','lista');">Galería</a>
        </div>

        <div id="opciones-orden">
            <strong>Opciones:</strong>  <a href="#listado" onclick="return show('lista','galeria');">Búsqueda</a> |
            <a href="#listado" onclick="return show('lista','galeria');">Ordenamiento</a>

        </div>


      </div>

      <div id="galeria">
        {% for libro in libros %}
          <div class="large-4 small-6 columns" data-equalizer-watch>
            <a href="libro/{{libro.id}}"><img src="{{MEDIA_URL}}{{libro.cover_url}}"></a>
            <div class="panel">
            <h5> <a href="/libro/{{libro.id}}">{{libro.titulo}}</a> </h5>
            <h6 class="subheader">{{libro.autor}}</h6>
            </div>


        </div>
         {% endfor %}
      </div>

<div id="lista" style="display:none">

  <div class="columns" id="users">
    <input class="search" placeholder="Buscar en la tabla" />
    <button class="sort" data-sort="titulo">
    Ordenar por titulo
    </button>
    <table>
    <thead>
    <tr>
      <th width="200">Titulo</th>
      <th  width="200"  >Autor</th>
      <th width="150">Editorial</th>
      <th> Fecha de publicación</th>
    </tr>
    </thead>
    <!-- IMPORTANT, class="list" have to be at tbody -->
    <tbody class="list">
      {% for libro in libros %}
      <tr>
        <td class="titulo"> <a href="/libro/{{libro.id}}">{{libro.titulo}}</a> </td>
        <td class="autor">{{libro.autor}}</td>
        <td class="editorial" >{{libro.editorial}}</td>
        <td class="fecha">{{libro.fecha_publicacion}}</td>


             {% endfor %}
          </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/libroDetalle.html
{% extends 'base.html' %}

{% block contenido %}
<br>
<div class="large-8 columns">
	<div class="row">
		<h3>Detalle libro</h3>
 		<div class="large-6 small-6 columns">
			<img style="position:realtive" src="{{MEDIA_URL}}{{libro.cover_url}}">
		</div>

		<div class=" panel large-6 small-6 columns">
			<h4> <strong>{{libro.titulo}}</strong> </h4>
			<p>Por <a href="">{{libro.autor}}</a> </p>
			<p>Editorial <strong>{{libro.editorial}}</strong> </p>
			<p>Fecha de publicación <strong>{{libro.fecha_publicacion}}</strong> </p>
			<p> Area <a href="">#{{libro.area}}</a> </p>
			<p> Facultad <a style="color:green;" href="">{{libro.get_facultad_display}}</a> </p>

			{% if libro.disponible_fisico %}

			<p style="color:red"> Puedes prestar este libro ! </p>

				<a style="background-color:#F25E5C" class="button tiny "  href="{{libro.id}}/prestamo">Prestar</a>


			{% else %}

			<p style="color:red">Libro no disponible para prestamo, pero puedes descargar una copia. !</p>

			<a style="background-color:#7bac0f" class="button tiny "  href="{{MEDIA_URL}}{{libro.digital_url}}">Descargar</a>

			{% endif %}










		</div>

	</div>
</div>

{% endblock %}

templates/libroForm.html
{% extends 'base.html' %}

{% block contenido %}
<br>
	  <div class=" large-8 columns">
      <h4><a href="/">Inicio</a> / Nuevo libro</h4>
      <div class=" panel large-10 small-11 columns">
        <form  enctype='multipart/form-data' action='' method='POST'>
            <div class="row">
                <p style="text-align:center; color:gray;"> <em> Datos generales</em></p>
                <div class="  large-12 columns">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            <label> Titulo:
                            {{ form.titulo }}
                            </label>
                            {% if form.titulo.errors %}
                     
                              {% for error in form.titulo.errors %}
                              <small class="error">
                                  {{ error|escape }}
                              </small>
                              {% endfor %}
                          {% endif %}
                          
                </div>
            </div>
            <br>

            <div class="row">
                  <div class="large-4 columns">
                            <label > Autor: 
                             {{ form.autor }}
                            </label>
                            {% if form.autor.errors %}
                     
                              {% for error in form.autor.errors %}
                              <small class="error">
                                  {{ error|escape }}
                              </small>
                              {% endfor %}
                          {% endif %}
                  </div>

                  <div class="large-4 columns">
                            <label > Area: 
                             {{ form.area }}
                            </label>
                            {% if form.area.errors %}
                     
                              {% for error in form.area.errors %}
                              <small class="error">
                                  {{ error|escape }}
                              </small>
                              {% endfor %}
                          {% endif %}
                  </div>

                  <div class="large-4 columns">
                            <label > Editorial: 
                             {{ form.editorial }}
                            </label>
                            {% if form.editorial.errors %}
                     
                              {% for error in form.editorial.errors %}
                              <small class="error">
                                  {{ error|escape }}
                              </small>
                              {% endfor %}
                          {% endif %}
                  </div>  
            </div>

            <div class="row">

              <div class="large-6 columns">
                            <label > Facultad: 
                             {{ form.facultad }}
                            </label>
                            {% if form.facultad.errors %}
                     
                              {% for error in form.facultad.errors %}
                              <small class="error">
                                  {{ error|escape }}
                              </small>
                              {% endfor %}
                          {% endif %}
              </div>


              <div class="large-6 columns">
                            <label > Fecha de publicación:
                             {{ form.fecha_publicacion }}
                            </label>
                            {% if form.fecha_publicacion.errors %}
                     
                              {% for error in form.fecha_publicacion.errors %}
                              <small class="error">
                                  {{ error|escape }}
                              </small>
                              {% endfor %}
                          {% endif %}
              </div>

              
            </div>

            <div class="row">

              <p style="text-align:center; color:gray;"> <em> Recursos</em></p>

              <div class="large-4 columns">
                            <label > Imagen de portada: 
                             {{ form.cover_url }}
                            </label>
                            {% if form.cover_url.errors %}
                     
                              {% for error in form.cover_url.errors %}
                              <small class="error">
                                  {{ error|escape }}
                              </small>
                              {% endfor %}
                          {% endif %}
              </div>
              <div class="large-4 columns">
                            <label > ¿Esta disponible en fisico?: 
                             {{ form.disponible_fisico }}
                            </label>
                            {% if form.disponible_fisico.errors %}
                     
                              {% for error in form.disponible_fisico.errors %}
                              <small class="error">
                                  {{ error|escape }}
                              </small>
                              {% endfor %}
                          {% endif %}
              </div>

              <div class="large-4 columns">
                            <label > Archivo Digital: 
                             {{ form.digital_url }}
                            </label>
                            {% if form.digital_url.errors %}
                     
                              {% for error in form.digital_url.errors %}
                              <small class="error">
                                  {{ error|escape }}
                              </small>
                              {% endfor %}
                          {% endif %}
              </div>




            </div>

              <br>
          <input style="background-color:#7bac0f" class="button tiny " type='submit' value='Registrar libro'/>

        
        </form>

        <p> ¿ No encuentras el autor ? <a href="{% url 'autores_nuevo' %}"> Registralo áca</a>  </p>
    
        </div>
      </div>








{% endblock %}

templates/libroNuevo.html
{% extends 'base.html' %}

{% block contenido %}
<br>

<div class="panel large-6 columns">

        		
<h4> Gracias por tu aporte, el libro se agrego correctamente !</h4> <a href="#"> Ver libro </a>

</div>
{% endblock %}

templates/librosListado.html
{% extends 'base.html' %}

{% block contenido %}
<br>
  <div class="large-8 columns">
    <div class="row" data-equalizer>

      <nav id="menu_estanteria">
        <ul>
          <li><strong>Descubre:</strong></li>
          <li>|</li>
          <li> <a style="color:red;" href="/titulos/">Títulos </a>  </li>
          <li>|</li>
          <li><a href="">Autores</a> </li>
          <li>|</li>
          <li><a href="">Temas</a> </li> 
          <li>|</li>
          <li><a href="">Facultades</a></li>
          <li>|</li>
        </ul>
      </nav>

      <div  class=" opciones columns"><h3> Todos los Títulos</h3> 

     
        <div id="opciones-vista">
          <strong>Vista:</strong>  <a href="#listado" onclick="return show('lista','galeria');">Listado</a> | <a href="" onclick="return show('galeria','lista');">Galería</a>
        </div>
        
      </div>
          
  <div class="columns" id="users">
    <input class="search" placeholder="Buscar en la tabla" />
    <button class="sort" data-sort="titulo">
    Ordenar por titulo
    </button>
    <table>
    <thead>
    <tr>
      <th width="200">Titulo</th>
      <th  width="200"  >Autor</th>
      <th width="150">Editorial</th>
      <th> Fecha de publicación</th>
    </tr>
    </thead>
    <!-- IMPORTANT, class="list" have to be at tbody -->
    <tbody class="list">
      {% for libro in libros %}
      <tr>
        <td class="titulo"> <a href="/libro/{{libro.id}}"></a> {{libro.titulo}}</td>
        <td class="autor">{{libro.autor}}</td>
        <td class="editorial" >{{libro.editorial}}</td>
        <td class="fecha">{{libro.fecha_publicacion}}</td>
              </tr>
             {% endfor %}
          </tbody>
          </table>
  </div>
</div>

{% endblock %}

templates/prestamoExito.html
{% extends 'base.html' %}

{% block contenido %}
<br>

<div class="panel large-6 columns">


<h4>  Tu prestamo se hizo correctamente !</h4> <a href="/"> Ver mas libros </a>

</div>
{% endblock %}